export const baseUrl = "https://nekopoi.care";
export const Yuumari = "https://yuumari.com/bypass"
export const endpoint = {
  release: "/category/hentai/page/$PAGE",
  genre: "/genres/$GENRE/page/$PAGE/",
  search: "/search/$KEYWORD/page/$PAGE",
  detailPage: "/hentai/$ID",
  hentai: "/hentai/page/$PAGE",
  episode: "/$ID"
};

export const genrelist = [
  'action',
  'anal',
  'bdsm',
  'blonde',
  'bondage',
  'creampie',
  'dilf',
  'exhibitionist',
  'female monster',
  'Footjob',
  'Furry',
  'Gangbang',
  'Harem',
  'Humilation',
  'Hypnotize',
  'Intercrural',
  'Loli',
  'Male Monster',
  'Megane',
  'Mind Control',
  'Netorare',
  'Old man',
  'Oral',
  'Pantyhose',
  'Prostitution',
  'Romance',
  'Schoolgirl',
  'Sex Toys',
  'Shota',
  'Succubus',
  'Swimsuit',
  'Threesome',
  'Tsundere',
  'Vanilla',
  'Yaoi',
  'Ahegao',
  'Armpit',
  'Big Oppai',
  'Blowjob',
  'Comedy',
  'Dark Skin',
  'Elf',
  'Fellatio',
  'Femdom',
  'Forced',
  'Futanari',
  'Gore',
  'Housewife',
  'Humiliation',
  'Incest',
  'Lactation',
  'Maid',
  'Masturbation',
  'MILF',
  'Monster',
  'Nurse',
  'Onee san',
  'Paizuri',
  'Pregnant',
  'Rape',
  'Saimin',
  'Semi Hentai',
  'Shibari',
  'Stocking',
  'Supranatural',
  'Tentacles',
  'Transsexual',
  'Uncensored',
  'Virgin',
  'Yuri',  
]
